version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 13.0.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: tests
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: gem install bundler -v 2.3.5
      - run: bundle install
      - run:
          name: Build and Run Tests
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  development:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master
