default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Run Tests"
  lane :tests do
    scan(
      package_path: "./",
      workspace: '.', # ignore .xcodeproj if it exists
      destination: 'platform=iOS Simulator,name=iPhone 12',
      scheme: "ActivityContentSDK",
      configuration: "Debug",
      code_coverage: true
    )
  end

end
