name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Show eligible build destinations for ActivityContentSDK
      run: xcodebuild -showdestinations -scheme ActivityContentSDK
    # - name: Build and test ( macOS 12.0 Monterey)
      # run: xcodebuild test -scheme ActivityContentSDK -destination 'platform:macOS, arch:x86_64, id:4203018E-580F-C1B5-9525-B745CECA79EB'
    - name: Build and test ( iOS 15.0)
      run: xcodebuild test -scheme ActivityContentSDK -destination "platform=iOS Simulator, OS=15.0, name=iPhone 12 Pro"
